=== Tinuz/openforensicfileformat/docs/schema/offf-job-manifest-0.1.0.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://offf.dev/schema/offf-job-manifest-0.1.0.schema.json",
  "title": "OFFF Job Manifest v0.1.0",
  "type": "object",
  "additionalProperties": false,
  "required": ["job_id", "created_at", "case_id", "task", "scope", "tool", "parameters"],
  "properties": {
    "job_id": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "case_id": {
      "type": "string",
      "pattern": "^urn:offf:case:.+$"
    },
    "task": {
      "type": "string",
      "enum": ["keyword_scan", "yara_scan"]
    },
    "scope": {
      "type": "object",
      "additionalProperties": false,
      "required": ["chunks"],
      "properties": {
        "chunks": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^(\\*|sha256:[0-9a-f]{64})$"
          }
        }
      }
    },
    "tool": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "version"],
      "properties": {
        "name": { "type": "string", "minLength": 1 },
        "version": { "type": "string", "minLength": 1 }
      }
    },
    "parameters": {
      "type": "object"
    }
  }
}

=== Tinuz/openforensicfileformat/tests/samples/keyword_job.json
{
  "job_id": "job-99187fea-6f03-47d7-9386-816e823c750d",
  "created_at": "2026-05-22T12:13:58.042218400Z",
  "case_id": "urn:offf:case:bbd5e65b-8b6c-498b-a2b5-9d558acb52b6",
  "task": "keyword_scan",
  "scope": {
    "chunks": [
      "sha256:961ea1211926c6c57d95899b3282c72c5ee24249d16e3ace82bd5273796f9f47",
      "sha256:42e16a0c6369670f953b949f671a899512d9cbb2d7ef4a1ad6a7ca75698f5ef1",
      "sha256:57b114ce3e00a955d0ed93be366263c83b454910360c6ccd5b42d90cbd7b7388",
      "sha256:42c64998b109eb67c8bed4d31a2244b15920a734475529c3bdab37e74bce9447",
      "sha256:875fdc50fcbfa87ef79765844d63a167ba876bb55cdc88f652f4a128f41ac895",
      "sha256:f86cf64d901401e61d620e89de45fcfd46c5321d008f421232d6553d47a26947",
      "sha256:a057f87e15543a8136ca65b7588cfcf54a6f54c8fb7b8bbfdddf8113a1fea295",
      "sha256:401fe5ef0f5b2b0aee66749b0aa6b58ff56e1670d21946c57086c28536a2e857",
      "sha256:b9f76b0827bace9ac1cf43ab9bbd3825ed4af2ff3e300b7dcdd58b3b3f8e0a02",
      "sha256:7489fdc5321d1d1bb66da89078555227e97c70c4549557852f99ed399f7b4cf8",
      "sha256:927af7f82f372c6f570b498c6b19c20ebba97697de29bcba3e670421f1bf4c48",
      "sha256:a66db0ad6cc27d09c0a31f749c91cffe91a3264bb492d7764f35815e613125ec",
      "sha256:19b553af89bf880e8ad1fca0534215953cdb4785a4590dd9c738329829aa7c02",
      "sha256:7a85076301f0e1fb84cb49b913ca94014520ef97de29a87f29316cb3756af7d6",
      "sha256:85226f5a4afb9b18e6492d06f7491f89b3da6400931550b024436efd965d917a",
      "sha256:b6ef4a8cec3f6d87dd041bcc30f9c0d469ef14de1cb60f314d1d03f8dab4b56d",
      "sha256:49928af68a35b04f9fee8cb3a01cdb1e0ba745c292f7f2a3064e52586f99c1e3",
      "sha256:792c864ef3db54cb666db8916f84e34b4a026550e86def9758e3a9a497f9a778",
      "sha256:8c74a9e80067a468a125bce3c3d8837007e0a034d5fc6017a402d93791180098",
      "sha256:fe1a2900f6acb27d8db146a69fe73c5a859f55a24c286f0ce15b469c876e8470",
      "sha256:038e6e8c96762a0173c250e346b59c9496ee03bcd83d6f7a7553065717e4f5cf",
      "sha256:841355f109abc85ebd77434e65875eb35ab53c7457c6fa0096085c0a79d0441b",
      "sha256:d1adb0b8731e4bdaaf12c31b0c4d27482fdc493453556315e51556da2812fca4",
      "sha256:fc9190f35d89a78c331787ab1a56aaa6d647e5ff2beacdc841afb28872d910c4",
      "sha256:a314e1c6f786e279eeb13fa680fd0586a84236da0c9edb1450cc7fb5155664cb",
      "sha256:3b7303c3ccaf65dd353923156df194f0e51546999867719a0eb410ea057d1f28",
      "sha256:b58321cfc60d7964c43effe6a014e70814c3549fbed9ad6bc818e22e161b5168",
      "sha256:97713a7a7da095037d82fb6b7d770527f7c747898a21bc4fa8b217551796f9a7",
      "sha256:ffc47c2c638c008b876d65d544fa3708067b90320762df6df6978e5bf7aa6776",
      "sha256:64e8a42b6a579538ff20408864ec3606c7c45cd3e20b54de75b445ca682f0f4e",
      "sha256:db019336f667acc33068193ccb744ebe8b94ac337d2c908a4bb09ab4baa6615f",
      "sha256:b8aa40119a48b3fd597a3a69cad181c87154ae1d3f497a6d3224cc53770fae86",
      "sha256:fe078138d027b46760bbd3154f5964defcafa4eb06a554d94ec3cfe31ac340c3",
      "sha256:4df22df5b2be5906d36b85a30ce875213a3bb93b2e3507ba05c57ed6c7ac102a",
      "sha256:75df746af91da801a31ce7627c6fb23fe8bd3adab25c5a88a1bd75d22add9909",
      "sha256:81c9fd415f299d76bf8f0fd86803fb033f3c84bdf1ba410ab6d2d6e53de3fb7d",
      "sha256:bdc62cea46f7fa9c25d0e0fb167e817e3438968be904ab9c339df0f8b89696e5",
      "sha256:f078e95a98182b716b86128142c731b8f585738c212b621cd4b133cc02ae6ff9",
      "sha256:546c49f3cda445baee4149a9d9ca8c89ca1ad6e685dc06d630b55442c4ce50a9",
      "sha256:066b305161d12e47b7a8f9864530336a2e3f454fd3e40aeb00484eb6eb98a49d",
      "sha256:972e935a164db99b38a7152175e1e18e1c5ceea3067daab60f2044d76d434004",
      "sha256:703ac1ed45af89dbee27c2515458f0a47453f8f159dedb1ac161940216f8327a",
      "sha256:b4fe765f21692e31b5624c47abb6be73cb5cd5add6a48a492550b635934d1b7f",
      "sha256:2afbfd218a3189e18cfdb9bd96af77c3bc66aead7dca71d100a36387f8d686fd",
      "sha256:49464f61286c9ce618877937d0b26ead429dcef9f45f696b0b58e6ec9c488d15",
      "sha256:24611658ef4fac5e6f1e69f5f66f3cf1052760d53aeb5bb7093f85f55e383e7c",
      "sha256:713607008dca8c33ed822a73888322904f88b5758cf819edc88f54b9bd58011b",
      "sha256:d17a545bd6920b2c8d6eaeb48e8f0fb85e41db4eb714cabda2bf2c907ae9da73",
      "sha256:3d0709b865ecd5870bd1e8fe34ad79ceec15fbe984edce4b307e4decb8a75f20",
      "sha256:541a7238578b97878c2ca06f3da8f94f2d1364e2b835a66f4e64517426276feb",
      "sha256:733b5fb6a09dca260aa4a96d456bed25697249ddb345c3cb0bc9b4cd59d2f88a",
      "sha256:e96bf3c6a44a0074c5c5ef0dd6772a02288bf10e7baafe68f5bbee7e6648794f",
      "sha256:33b43a904f83a1e466ced752157febef7e300c5167abab2ec28a5216f863c45b",
      "sha256:e13489586990244a179a7d761175738a1c6239e86d6a5cbb09fc7e72d4babb40",
      "sha256:2e9b5da6d891b7702db521e0a2d1ba80b0f81b88766495cdd292ae106bab05fe",
      "sha256:0baee569005f80dcef66a7c3b1fd1caeae22cb9de66bace4b4afc5acb9ba4f20",
      "sha256:66bff41ab4612a36d4c3dd5e786e17d513ea81b333760ad48a8ea916fc0ac549",
      "sha256:25da6b35bc843dd555fd22d944d4ff03a062dddd012d8ad0fbfd1f6a3642da2f",
      "sha256:e5b6fac8a9df0df866acb0dda9bf24cfcecef5b7ec1e7ce49f215088cc4669c9",
      "sha256:a1d036330358cee14b1568780fbbdf583ea29a1c9412039da1c38723d154a586",
      "sha256:4d3c7047d9db42efc079b4dfdd2f3fd2af8ccd19438abc8ad3e19f4b9f94f786",
      "sha256:6576b3a8c9245f042b774e2128542afb0fa071ea8846039de403fa68e728dfa6",
      "sha256:72731356c3ae6de88548cebc256aa738cab3fd48b43d6c73a72a4cf81a902c58",
      "sha256:2fa6efe7ca013ac88d4d374f703d7d7980f59ebd4fe3a0bfeecc61f0cb205631",
      "sha256:c7525a6b2eed638fa81c872099ef48e1cb5fde5af1a3851371e60042d73f37a5",
      "sha256:8cdc99c4c1d60332cd44f13c4d94ec446d146d6f81941b2ed83f68821da4a5fa",
      "sha256:27b024bda5279667c26e89f664f2b4584486e008db479f0b61382a78af7776b0",
      "sha256:802deac62dc40efe9caa2acbe1c978ca9f852d24a79f8d12fe312153981f3307",
      "sha256:b3a7c50c2632203cfe261629f122fb7ece9286842526fc250067644e58b0da07",
      "sha256:61975b9af55cd9768267d7de804ad3b55af7679626ea90264e07658fbdf7fc0f",
      "sha256:49516c329dfca6696f7b862516c469641e692eab43d8c7d69a3e8aad5dd2580b",
      "sha256:36b2fa1226879d24a355f04ddc3c5cdfdb3ce9123ad6e70ca3b86ff238697223",
      "sha256:200eee0150c176b63c23351eddc28e11dcdc01bf75302557e7d3251f5e2da428",
      "sha256:4de5f01cf8aa1e877bdefeca71c65bf516e631ebd5b54f9d39fc035dc28e11f9",
      "sha256:7a8c43698e758e07154a21a359e7e738c75af3bdfe8a187d6bb8b1f66adc3e80",
      "sha256:bf4f7f8c617e7265e87fd009f7352c8884dae54a556ad8829bfaa837b4299b6c",
      "sha256:520cbcb4bc3c27c4fea6dc60a3583b60665eb381041aeb2b3728f247a61a999f",
      "sha256:af4dd760c4f13fe656cddbc6a8b681ef19996be47f0d54b4473c3751f0ba01ed",
      "sha256:a68375399ea3ff3415696fea7572f4b7bf0d5875bd123ead902613939a867028",
      "sha256:3a914cc2ce6b40200ae1b7708bee56438e90d050be410a9dc9fa509843057214",
      "sha256:dd646fea1974f1f39d297ac63d9ec58f90e893ca33c8afcc5de51b6b03178fc1",
      "sha256:60bb21e50fcfe4ca01da546a1240b9fc4db381b3c302f899c3a4843b2aae155d",
      "sha256:ee058b82a58aba42a9b7315b8b850cb69641e20c9fbbb89d8ae7f8e33e1fef28",
      "sha256:9837270bdad92a0a005e220f01ea59d8ebd93c27464d2c7e6d091eb772134dcc",
      "sha256:ffce9bebfe9730f4b0091a2328f04808ba23fab17195107d0faae89e9bd9bdbd",
      "sha256:9690567f96f128f48be381882c69372ea33152a118cd69000198dab505a00047",
      "sha256:b175c82da6b067d343c1ee68196d75135ee8129f91fa474b9774430199390cfb",
      "sha256:75229b85970ab19d4ab84eeef4ef7c23416ab60f8f24adde503e56c2987e4496",
      "sha256:80a7e9d13cf2235b733cd5cca8098bc48edb0e6d4fe38be86af372121e2e19b4",
      "sha256:d1ce3944f4d6e1f1681526e36f364107664214eb1c7a0e64f2c779e1200fdcc2",
      "sha256:c83ad21326d3e98ef209aa3a745f1c1c7938d758a34c983c9c1f564fa254bdde",
      "sha256:74969197fd8c6cc6ade7a5863a0b46210039513867c755872f824d56bd3ca197",
      "sha256:5594a4b12fd8ebcd51de6b4e5081ff18fa6ad9d61647e4e066be0ff901371f2d",
      "sha256:07cd4fc4404c38e37d48b318735ff013eab7430fe291b4897b51944b50184663",
      "sha256:557e120c8d02ccabe9c76f325d8a75a244a378fe3ba5a4494fee25c62636977a",
      "sha256:f4da9fe99740d9fa8207479925376975c89f007e63c2afd475c5441835866fe0",
      "sha256:1a5356d7be5ed7663af2576520162bdab823bb2ef9d86b64826e5de7b57760be",
      "sha256:9865bd51054af6b80789a4ca0040328802efcd8ddd0c99d194a62320dd7ec368",
      "sha256:2192472a7d3d9b62236ff2978047e362307b7328fcfb2c21b2290e45233c0ea7",
      "sha256:a2cac11788789cc45a0e7ef7109e63150764db0860365f070aefa723db927461",
      "sha256:eb3218001e67e03ec60058c10bcf41494b97265dfb0e182b2c3589ee32c3ff5e",
      "sha256:96da72cc7b1290a854198770ecba53b0ab677c08d12a025f6b80fc2ba3abb912",
      "sha256:402a1b5ccc75006a5b398e362eb8da472f865beb3eb130f8ebb7dd1b09295038",
      "sha256:d2e7fb75ded7fc1ee88bd022a1f3b8933350989b43044fd13dbad4653c6bb164",
      "sha256:643fed537833cbde5b2c720ed06de1d4addfd98cc526b3fe644b5556428e0645",
      "sha256:18dbdf08793dde577ff0d9a26a0ff2f11e78c0e6889d475188aa09b14362ea6a",
      "sha256:faea05fda5fae4f1751f64e6328b7e57c4f668bc79a34c16473b77ff9884fcf6",
      "sha256:be1cea5d8624f622fd864600764043677b3d19f4c6093cbd284ba9462deb3f56",
      "sha256:2d33043cecbc42e8b1cf2343b34d61e9d98a9618e719b83d5c83d8bbcaf9112d",
      "sha256:08c10dc7ca4ec4f67ef8f69f7ea180f231864b7dc5a1fc677cbe9acca29a58b1",
      "sha256:7c8f8e1f23a5516de4ad0ba3ca104a50a7183c9a86b5ff4b72789fbc43d8a9d7",
      "sha256:90b9cfacdbed7c006315cd925275b051872776bb1842b0f52bfa9149ec097156",
      "sha256:d954fcbe423863df1d0694208b140cf0453588f4d9f08198ffb5dc9c098f51ef",
      "sha256:c5c70be52ae0ebec243032c9a518a4a0dd919804320c58758489d9ab0ce14c1e",
      "sha256:4a31c92ccbb891ac93ee83c943c89c30eab387c0b7e7582de84a293b4d387846",
      "sha256:ecb4e6577dc8ec8526e5bcc108dabb5026dc7e9bb08c4873e93b2ca04c0142fc",
      "sha256:323aaab8d8c7865c845cc9589490a65655b92e4bfacbf2a4e9e04b5c0209242e",
      "sha256:cd168d084d435985e68a2d1cc4f77bef5d347474497901e3468fd525c9995931",
      "sha256:b1aaca7a1c806e75bfc4a808fd6daf8a1824663c021014f5fdd4f8166f067205",
      "sha256:1ff1f5d67bad71aa1d4428e547caa00a1de20eee81bd808ce9bf67f305c06d27",
